apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: funixproductions-dev-dashboard-certificate
  namespace: "funixproductions-dev"
spec:
  secretName: funixproductions-dev-dashboard-certificate-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "dev-dashboard.funixproductions.com"
  dnsNames:
    - "dev-dashboard.funixproductions.com"
