name: Build dev env

on:
  push:
    branches: [ master ]

jobs:
  build-production-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dashboard funixproductions dev
        run: |
          docker build . --tag ghcr.io/funixproductions/funixproductions-dashboard:dev
          docker push ghcr.io/funixproductions/funixproductions-dashboard:dev

  update-kubernetes-cluster:
    needs:
      - build-production-image

    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Update Kubernetes Cluster
        run: cd kubernetes-dev && chmod +x ./deploy.sh && ./deploy.sh
