name: Build dev env

on:
  push:
    branches: [ master ]

jobs:
  build-production-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    environment:
      name: development
      url: https://dev.dashboard.funixproductions.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/funixproductions/funixproductions-dashboard:dev

  update-kubernetes-cluster:
    needs:
      - build-production-image

    runs-on:
      - self-hosted
      - k3s-funixproductions

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Update Kubernetes Cluster
        run: cd kubernetes-dev && chmod +x ./deploy.sh && ./deploy.sh
