name: Build production

on:
  push:
    branches: [ master ]

jobs:
  build-pterodactyl-image-and-restart-prod:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push funix api pterodactyl dockerfile
        run: |
          docker build . --tag ghcr.io/funixproductions/funixproductions-dashboard:latest
          docker push ghcr.io/funixproductions/funixproductions-dashboard:latest
