name: Build production

on:
  release:
    types: [created]

jobs:
  build-production-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (for cross-building)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/funixproductions/funixproductions-dashboard:latest

  update-kubernetes-cluster:
    needs:
      - build-production-image

    runs-on: k3s-funixproductions

    environment:
      name: production
      url: https://dashboard.funixproductions.com

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Update Kubernetes Cluster
        run: cd kubernetes && chmod +x ./deploy.sh && ./deploy.sh
